version: '3.3'
services:
  rcnapp:
    image: rcnapp
    restart: always
    networks:
      - my-network
  rcnappui:
    image: registry.gitlab.com/dsl94/rcnapp
    restart: always
    networks:
      - my-network
  nginx-proxy:
    build:
      context: ./proxy
    ports:
      - "80:80"
    networks:
      - my-network

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8090:8080

networks:
  my-network: