version: '3.3'
services:
  rcnapp:
    image: rcnapp
    restart: always
    networks:
      - my-network
  rcnappui:
    image: registry.gitlab.com/dsl94/rcnapp
    restart: always
    networks:
      - my-network
  nginx-proxy:
    build:
      context: ./proxy
    ports:
      - "80:80"
    networks:
      - my-network

networks:
  my-network: